const menuItems = [
    {
        id: 1,
        name: "Let's Go Simples",
        description: "Burger artesanal 150g, queijo cheddar, presunto e salada.",
        price: 16.49,
        image: "/Burger/noImage.png",
        type: "artesanal",
    },
    {
        id: 2,
        name: "Let's Go Duplo",
        description: "Dois burgers artesanais 150g, queijo cheddar duplo e bacon.",
        price: 22.99,
        image: "/Burger/noImage.png",
        type: "artesanal",
    },
    {
        id: 3,
        name: "Let's Go Bacon",
        description: "Burger artesanal 150g, queijo cheddar e bacon crocante.",
        price: 18.99,
        image: "/Burger/noImage.png",
        type: "artesanal",
    },
    {
        id: 4,
        name: "Let's Go Eggs",
        description: "Burger artezanal 150g, ovo, queijo cheddar, presunto e salada.",
        price: 24.49,
        image: "/Burger/noImage.png",
        type: "artesanal",
    },
    {
        id: 5,
        name: "Let's Go Calabresa",
        description: "Calabresa fatiada 170g, ovo, queijo cheddar, presunto e salada.",
        price: 16.49,
        image: "/Burger/noImage.png",
        type: "tradicional",
    },
    {
        id: 6,
        name: "Let's Go Frango",
        description: "Frango em cubos 170g, ovo, queijo cheddar, presunto e salada.",
        price: 16.49,
        image: "/Burger/LetsFrango-1.png",
        type: "tradicional",
    },
    {
        id: 7,
        name: "Let's Go Calafrango",
        description: "Calabresa fatiada 85g, frango em cubos 85g, ovo, queijo cheddar, presunto e salada.",
        price: 17.49,
        image: "/Burger/LetsCalafrango-1.png",
        type: "tradicional",
    },
    {
        id: 8,
        name: "Let's Go Carne do Sol",
        description: "Carne do sol em cubos 190g, ovo, queijo cheddar, cebola caramelizada, presunto e salada.",
        price: 23.99,
        image: "/Burger/noImage.png",
        type: "tradicional",
    },
    {
        id: 9,
        name: "Let's Go Alcatra",
        description: "Carne de alcatra em cubos 190g, ovo, queijo cheddar, cebola caramelizada, presunto e salada.",
        price: 26.49,
        image: "/Burger/LetsAlcatra-1.png",
        type: "tradicional",
    },
    {
        id: 10,
        name: "Coca-Cola 1L",
        description: "Garrafa",
        price: 7.00,
        image: "/Refris/coca1l-2.png",
        type: "refrigerante",
    },
    {
        id: 11,
        name: "Guaraná 1L",
        description: "Garrafa",
        price: 6.00,
        image: "/Refris/guarana1l.png",
        type: "refrigerante",
    },
    {
        id: 12,
        name: "Coca-Cola 350ml",
        description: "Lata",
        price: 5.00,
        image: "/Refris/refri-1.png",
        type: "refrigerante",
    },
    {
        id: 13,
        name: "Guaraná 350ml",
        description: "Lata",
        price: 5.00,
        image: "/Refris/refri-2.png",
        type: "refrigerante",
    },
    { 
        id: 14,
        name: "Suco de Maracujá", 
        description: "Suco natural de Maracujá", 
        price: 7.99, 
        image: "/Sucos/sucoMaracuja.png", 
        type: "suco", 
        juiceType: "agua" 
    },
    {  
        id: 15, 
        name: "Suco de Cajú", 
        description: "Suco natural de Cajú", 
        price: 7.99, 
        image: "/Sucos/sucoCaju.png", 
        type: "suco", 
        juiceType: "agua" 
    },
    { 
        id: 16,
        name: "Suco de Acerola", 
        description: "Suco natural de Acerola", 
        price: 7.99, 
        image: "/Sucos/sucoAcerola.png", 
        type: "suco", 
        juiceType: "agua" 
    },
    {   
        id: 17,
        name: "Suco de Goiaba", 
        description: "Suco natural de Goiaba", 
        price: 7.99, 
        image: "/Sucos/sucoGoiaba.png", 
        type: "suco", 
        juiceType: "agua" 
    },
    {   
        id: 18,
        name: "Suco de Graviola", 
        description: "Suco natural de Graviola", 
        price: 7.99, 
        image: "/Sucos/sucoGraviola.png", 
        type: "suco", 
        juiceType: "agua" 
    },
    { 
        id: 19,
        name: "Suco de Maracujá", 
        description: "Suco natural de Maracujá", 
        price: 7.99, 
        image: "/Sucos/sucoMaracuja.png", 
        type: "suco", 
        juiceType: "leite" 
    },
    {   
        id: 20,
        name: "Suco de Cajú", 
        description: "Suco natural de Cajú", 
        price: 7.99, 
        image: "/Sucos/sucoCaju.png", 
        type: "suco", 
        juiceType: "leite" 
    },
    { 
        id: 21,
        name: "Suco de Acerola", 
        description: "Suco natural de Acerola", 
        price: 7.99, 
        image: "/Sucos/sucoAcerola.png", 
        type: "suco", 
        juiceType: "leite" 
    },
    {   
        id: 22,
        name: "Suco de Goiaba", 
        description: "Suco natural de Goiaba", 
        price: 7.99, 
        image: "/Sucos/sucoGoiaba.png", 
        type: "suco", 
        juiceType: "leite" 
    },
    {  
        id: 23, 
        name: "Suco de Graviola", 
        description: "Suco natural de Graviola", 
        price: 7.99, 
        image: "/Sucos/sucoGraviola.png", 
        type: "suco", 
        juiceType: "leite" 
    },
    {   
        id: 24,
        name: "Água (Sem gás)", 
        description: "Água mineral", 
        price: 7.99, 
        image: "/Sobremesa/aguaMineral-3.png", 
        type: "aguaSemGas",
        juiceType: "mineral"
    },
    {   
        id: 25,
        name: "Água (Com gás)", 
        description: "Água com gás", 
        price: 7.99, 
        image: "/Sobremesa/aguaMineral-3.png", 
        type: "aguaComGas", 
        juiceType: "mineral"
    },
    {
        id: 26,
        name: "Pudim de Leite Condensado",
        description: "Clássico pudim caseiro com calda de caramelo.",
        price: 8.50,
        image: "/Burger/noImage.png",
        type: "sobremesa",
    },
    {
        id: 27,
        name: "Brigadeiro Gourmet",
        description: "Brigadeiro feito com chocolate belga e granulado premium.",
        price: 4.00,
        image: "/Burger/noImage.png",
        type: "sobremesa",
    },
    {
        id: 28,
        name: "Torta de Limão",
        description: "Base crocante, recheio cremoso de limão e cobertura de merengue.",
        price: 9.00,
        image: "/Burger/noImage.png",
        type: "sobremesa",
    },
    {
        id: 29,
        name: "Brownie com Sorvete",
        description: "Brownie quente com uma bola de sorvete de creme.",
        price: 12.00,
        image: "/Burger/noImage.png",
        type: "sobremesa",
    },
  ];
  
  export default menuItems;
  